# Conda environment file for developers
name: hdl21-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # HDL21
  - python=3.9
  - pydantic=1.9.1
  #  Install vlsir in editable mode  (pip install --no-deps -e .)
  #  Install vlsirtools in editable mode manually  (pip install --no-deps -e .)
  # VLSIRtools
  - numpy=1.21.5
  - pandas
  # HDL21 dev
  - pytest=7.1
  - coverage
  - pytest-cov
  - pre-commit=2.20
  - black=22.6
  - twine
